### ISSUE TITLE
loss of tab context

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#157]
Hi @abidibo,

I noticed that since I upgraded to v2, the tabs in change forms are not mapped to distinct urls. An unfortunate consequence is that when one is editing an object in a given tab, hitting 'save and continue' will lose the currently open tab.

Is there a way to avoid losing this tab context when saving?

Thanks!

**Comment by etanter** [comment]
I agree 100%... I didn't like the fact that that the back button was scrolling back through the tab history, and now I don't like the fact that saving loses the context.
One wants both... is there a way to hack around one way or another?
- With hashed URLs, one would need a way to redefine the behavior of the browser back button (which may not be possible), or to offer a convenient alternative button (eg. on the top left of the main space).
- With plain URLs, maybe one could store the current tab somewhere (in the session?) in order to reestablish it after save?

**Comment by etanter** [comment]
oh right, I forgot about the breadcrumbs (I have them disabled in my app)

**Comment by abidibo** [comment]
@etanter addresses in develop branch

**Comment by etanter** [comment]
Hi @abidibo,
I can't get it to work. 
I did: 
```
pip install git+git://github.com/otto-torino/django-baton.git@master          
```
but I can't see any change in the behavior. 
Am I doing stg wrong to install the dev branch?

Otherwise maybe it's a problem that I have admin templates overriden?

**Comment by abidibo** [comment]
@etanter develop branch at the moment, I'll merge it in master when releasing 2.1.6

**Comment by etanter** [comment]
It still doesn't work, with the develop branch. 
How can I check that I'm indeed running the proper version? I was hoping there were some attribute like `Baton.version`  that I could look at in the JS console, but wasn't able to find it.

**Comment by abidibo** [comment]
`baton.min.js` should contain

```
a()('a[data-bs-toggle="tab"]').on("shown.bs.tab",(function(t){a()(t.target).parents("form").attr("action",a()(t.target).attr("data-bs-target"))
```
![Uploading sec.gif…]()

**Comment by etanter** [comment]
Got it, it was a cache issue with the browser, I tried with an incognito window and it does work indeed.

Thanks a lot!

**Comment by etanter** [comment]
Great fix, btw! The best of both worlds!

**Comment by etanter** [comment]
@abidibo one slight limitation of the fix: when you reload a page (cmd-r) it will jump to the last tab where you saved, instead of staying on the current tab.

**Comment by etanter** [comment]
likewise, on some change forms I have a button that performs an action via a view, and then reloads the same page. So the context is then lost.

**Comment by abidibo** [comment]
@etanter ,
I can't do anything about it. The only way to achieve it would be to set the hash, but then I would introduce again the back navigation problem.
I've solved the save and continue issue by manipulating the `action` attribute of the form. So in order for it to work you actually need to submit the form.

As a side note you can decide to open a tab on load just by setting yourself the hash, i.e. `#fs-flags`. Baton will use it to activate the right tab.

**Comment by etanter** [comment]
for my button/view, indeed, I can just add the hash myself, duh! :)

In fact now with the save button adding the hash, it also ends up interfering with the back button. If I save and continue in different tabs, then the back button makes me travel back through all visited+saved tabs again.
So that's overall better than the past situations (v1 and v2), but still not perfect. Web apps over http! 

Maybe it's possible to use [replaceState](https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState) or [deleteUrl](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/history/deleteUrl) to remove the hashed urls from the history?

**Comment by etanter** [comment]
@abidibo what do you think about my suggestion? does it sound feasible?

**Comment by abidibo** [comment]
@etanter  maybe keeping the tab hashes and using deleteUrl or replaceState to keep the history clean can work. It needs some work though, I'll look into it as soon as I have a bit more time, thanks

**Comment by abidibo** [comment]
@etanter  I implemented it in develop branch

**Comment by etanter** [comment]
@abidibo this works great! 

one question: how would you suggest I deal with buttons that perform some action through a view and should then remain on the same tab?
what I'm doing now is adding the hash of the tab:
```
HttpResponseRedirect(request.META.get('HTTP_REFERER', '/') + '#group-fs-info')
```
but of course this now means that pressing the back button first reloads the change form without the tab hash.

thanks!

**Comment by etanter** [comment]
hmm, I can't get it to work. I installed (via pip) the current develop branch, and is trying in an incognito window in order to make sure I don't get betrayed by the cache, but I still see the same behavior: after saving the tab hash is in the url, so the back button rolls back through tabs in which I saved.
(as for making sure I'm indeed using the latest develop version, see issue #168)

**Comment by abidibo** [comment]
@etanter that's correct behavior, actually you've visited all that pages, and those pages stay in the history stack. I understand what you're saying but I fear what you mean is not possible. I won't use the `deleteUrl` API also because is not supported in Safari. The only thing I could do was to avoid creating a new history item when moving around tabs.
Imagine you start from a news changelist page
```
history = ['news-changelist']
```
then you edit news id 1:
```
history = ['news-changelist', 'news-changeform-id1']
```
now you change tab. Here, instead of adding an item, I replace the current one, so:
```
history = ['news-changelist', 'news-changeform-id1#tab']
```
now you submit and continue, you are redirected to the same page

```
history = ['news-changelist', 'news-changeform-id1#tab', ''news-changeform-id1#tab'']
```

you go to tab2

```
history = ['news-changelist', 'news-changeform-id1#tab', ''news-changeform-id1#tab2'']
```
and so on...

**Comment by etanter** [comment]
I see, breaking compatibility with Safari is indeed not a good idea. Well, anyway, you're right that having browsing not affecting the history is probably good enough.
Thanks again!
