### ISSUE TITLE
uncollapse inline entry when adding new one

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#70]
Hi,
Thanks for adding the possibility to collapse/expand individual entries in inlines (#65).

There's one small detail though, which is that when clicking on "add new xxx" in the inline list, the new one is also collapsed, which is a bit confusing for users. Is it possible to ensure that an entry being created is by default expanded? (while others are collapsed by default)

Cheers,
Éric

**Comment by abidibo** [comment]
yeah I know this, but there's no "easy" way of doing it without overriding django js utilities, and that's something I prefer not to do. The problem is that the add button actually clones a hidden element, with all its attributes, and so will clone also the `collapsed` css class

**Comment by etanter** [comment]
Oh, I see. Do you know how to "hack" this around? (not integrating the hack in baton, but just so that I can fix it locally)

**Comment by etanter** [comment]
thinking out loud: if the behavior of `collapse-entry` would be "collapse all except the first", would that fix the problem because now django js would clone the (uncollapsed) first entry?

**Comment by abidibo** [comment]
@etanter try the develop branch, should fix it

**Comment by etanter** [comment]
@abidibo just did `pip install https://github.com/otto-torino/django-baton/archive/develop.zip`, relaunched my django instance, hard-reloaded the pages, but no, still see the same problem.

**Comment by abidibo** [comment]
@etanter ,
can you please try with the new release 1.9.0, it works fine for me

**Comment by etanter** [comment]
yes, it works perfectly! (I see also that now one can click anywhere in the header to expand, which is exactly what one wants)
Thanks!
